import Head from 'next/head'
import { RegisterNumber } from '../src/pages'

export default function Home() {
  return (
    <div>
      <Head>
        <title>App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <RegisterNumber />
    </div>
  )
}
